# Generated by Django 5.2.5 on 2025-08-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('sales_view', 'Can view sales'), ('sales_manage', 'Can manage sales'), ('invoices_view', 'Can view invoices'), ('invoices_manage', 'Can manage invoices'), ('stock_view', 'Can view stock'), ('stock_manage', 'Can manage stock'), ('purchasing_view', 'Can view purchasing'), ('purchasing_manage', 'Can manage purchasing'), ('users_manage', 'Can manage users & roles')],
            },
        ),
    ]
