# Generated by Django 5.2.5 on 2025-10-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'permissions': [('sales_view', 'Can view sales'), ('sales_manage', 'Can manage sales'), ('invoices_view', 'Can view invoices'), ('invoices_manage', 'Can manage invoices'), ('stock_view', 'Can view stock'), ('stock_manage', 'Can manage stock'), ('purchasing_view', 'Can view purchasing'), ('purchasing_manage', 'Can manage purchasing'), ('users_manage', 'Can manage users & roles'), ('warehouse_view', 'Can view warehouse module'), ('warehouse_manage', 'Can manage warehouse module'), ('warehouse_admin', 'Can administrate warehouse module'), ('materials_view', 'Can view materials'), ('materials_manage', 'Can manage materials'), ('categories_view', 'Can view categories'), ('categories_manage', 'Can manage categories'), ('suppliers_view', 'Can view suppliers'), ('suppliers_manage', 'Can manage suppliers'), ('stock_movements_view', 'Can view stock movements'), ('stock_movements_manage', 'Can manage stock movements'), ('purchase_orders_view', 'Can view purchase orders'), ('purchase_orders_manage', 'Can manage purchase orders'), ('purchase_orders_receive', 'Can receive purchase orders'), ('dashboard_view', 'Can view warehouse dashboard')]},
        ),
    ]
