# Generated by Django 5.2.5 on 2025-09-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('SHOWROOM', 'Showroom / POS'), ('SOCIAL', 'Social media'), ('WHATSAPP', 'WhatsApp / Phone'), ('WEBSITE', 'Website'), ('MARKET', 'Marketplace'), ('FACTORY', 'Factory / Wholesale'), ('DEPOT', 'Depot'), ('OTHER', 'Other')], db_index=True, default='SHOWROOM', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sales_point',
            field=models.ForeignKey(help_text='Where this order was initiated (showroom, social media, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.salespoint'),
        ),
    ]
