# Generated by Django 5.2.5 on 2025-09-02 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quote_quoteline_quote_sales_quote_status_beb48d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
