# Generated by Django 5.2.5 on 2025-10-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBAN/RIB'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nif',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_delay',
            field=models.IntegerField(blank=True, help_text='Nombre de jours pour le paiement', null=True, verbose_name='Délai de paiement (jours)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('bank', 'Virement bancaire'), ('check', 'Chèque'), ('credit', 'Crédit')], max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RC'),
        ),
    ]
